trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        modifyOutputPath: false
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        projects: 'src/SecureMigrationsSample.Web/SecureMigrationsSample.Web.csproj'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: app

- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy application
    environment: production
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract application
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/app/*.zip'
              destinationFolder: '$(System.DefaultWorkingDirectory)/work'

          - script: |
              env ConnectionStrings:DefaultConnection="$CONN_STRING" dotnet '$(System.DefaultWorkingDirectory)/work/SecureMigrationsSample.Web.dll' --migrate --thenExit
            env:
              CONN_STRING: $(connectionString)
            displayName: Run database migrations
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: Deploy application
            inputs:
              appType: webAppLinux
              azureSubscription: 'SECURED_MIGRATIONS_WEBAPP'
              appName: 'securedmigrationssample'
              package: '$(Pipeline.Workspace)/app/*.zip'
