variables:
  connectionString: ''

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        modifyOutputPath: false
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        projects: 'src/SecureMigrationsSample.Web/SecureMigrationsSample.Web.csproj'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download application
      inputs:
        buildType: current
        artifactName: drop

    - task: ExtractFiles@1
      displayName: Extract application
      inputs:
        archiveFilePatterns: '$(System.ArtifactsDirectory)/drop/*.zip'
        destinationFolder: '$(System.DefaultWorkingDirectory)/work'

    - script: |
        env ConnectionStrings:DefaultConnection="$(connectionString)" dotnet '$(System.DefaultWorkingDirectory)/work/SecureMigrationsSample.Web.dll' --migrate --thenExit
      displayName: Run database migrations

#    - task: AzureWebApp@1
#      displayName: Deploy application
#      inputs:
        